config/routes.rb
BusTimetable::Application.routes.draw do
root :to => 'stations#index'
 resources :stations
 resources :lines
 resources :stops
 resources :publics
 resources :buses
 resources :maps
end

app/models/bus.rb
class Bus < ActiveRecord::Base
  has_many :stops
  # has_many :times, through: :stops
  has_many :stations, through: :stops
  belongs_to :line
end

app/models/line.rb
class Line < ActiveRecord::Base
  has_many :buses
  has_many :stops, through: :buses
  has_many :stations, through: :stops
  # has_many :time, through: :stops

  validates :name, :presence => true
  validates :name, :uniqueness => true
end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :stops
  # has_many :times, through: :stops
  has_many :buses, through: :stops
  has_many :lines, through: :buses

  validates :name, :presence => true
  validates :name, :uniqueness => true
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :station
  belongs_to :bus
  # has_many :times
  has_many :lines, through: :buses


validates_uniqueness_of :station_id, :scope => :bus_id
validates :station_id, :presence => true
validates :bus_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
def index
    @buses = Bus.all
  end

  def new
    @bus = Bus.new
  end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      flash[:notice] = "Bus created."
      redirect_to buses_path
    else
      render 'new'
    end
  end

  def show
    @bus = Bus.find(params[:id])
  end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    if @bus.update(bus_params)
      flash[:notice] = "Bus updated."
      redirect_to bus_path(@bus)
    else
      render 'edit'
    end
  end

  def destroy
    @bus = Bus.find(params[:id])
    @bus.destroy
    flash[:notice] = "Bus deleted."
    redirect_to buses_path
  end

  private
  def bus_params
    params.require(:bus).permit(:name, :line_id)
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(line_params)
    if @line.save
      flash[:notice] = "Line created."
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def show
    @line = Line.find(params[:id])
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(line_params)
      flash[:notice] = "Line updated."
      redirect_to line_path(@line)
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = "Line deleted."
    redirect_to lines_path
  end

  private
  def line_params
    params.require(:line).permit(:name)
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
    @stations = Station.all
    @lines = Line.all
    @stops = Stop.all
    render('index.html')
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Station created."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def show
    @station = Station.find(params[:id])
    @lines = Line.all
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(station_params)
      flash[:notice] = "Station updated."
      redirect_to station_path(@station)
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = "Station deleted."
    redirect_to stations_path
  end

  private
  def station_params
    params.require(:station).permit(:name)
  end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
def index
    @stops = Stop.all
  end

  def new
    @stop = Stop.new
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      flash[:notice] = "stop created."
      redirect_to stops_path
    else
      render 'new'
    end
  end

  def show
    @stop = Stop.find(params[:id])
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(stop_params)
      flash[:notice] = "Stop updated."
      redirect_to stop_path(@stop)
    else
      render 'edit'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    flash[:notice] = "Stop deleted."
    redirect_to stops_path
  end

  private
  def stop_params
    params.require(:stop).permit(:station_id, :bus_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buses/edit.html.erb
<% content_for(:title, "Edit Bus| Bus Timetable") %>

<h1> Edit Bus </h1>
<hr>

<%= render("layouts/bus_form", :object => @bus) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/buses/index.html.erb
<% content_for(:title, "All buses | Bus Timetable") %>

<h1> buses </h1>
<hr>
<ul>
<% @buses.each do |bus| %>
  <li><%= link_to "#{bus.name}", bus_path(bus) %></li>
<% end %>
</ul>

<%=link_to "New bus", new_bus_path, :class => "tiny button " %>
<%= link_to "Back", publics_path, :class => "tiny button" %>

app/views/buses/new.html.erb
<% content_for(:title, "Add Buses | Bus Timetable") %>

<h1> New Buses </h1>
<hr>

<%= render("layouts/bus_form", :object => @bus) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/buses/show.html.erb
<% content_for(:title, "#{@bus.name} | Bus Timetable") %>

<h1><%= @bus.name %></h1>

<h3>Here is the bus line: </h3>

<h4><%= @bus.line.name %></h4>

<h3>Here are the stations for the <%= @bus.name %> line:</h3>
<ul>
<% @bus.stations.each do |station| %>
  <li><%= link_to "#{station.name}", station_path(station)%></li>
  <% end %>
</ul>


<p><%= link_to "Edit", edit_bus_path, :class => "tiny button" %></p>
<p><%= link_to "Delete", bus_path, :class => "tiny button", :confirm => "Are you serious?", :method => "delete" %>

<p><%= link_to "Back", publics_path, :class => "tiny button" %></p>

app/views/layouts/_bus_form.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(object) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class => "tiny button") %>
<% end %>

app/views/layouts/_form.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(object) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "tiny button") %>
<% end %>

app/views/layouts/_stop_form.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(object) do |f| %>
  <div class="form-group">
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.collection_select :station_id, Station.all, :id, :name %>
  </div>

  <%= f.submit(:class => "tiny button") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= yield(:title) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <div class="row">
        <div class="large-12 columns">
          <%= flash[:alert] %>
          <%= flash[:notice] %>
            <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/lines/edit.html.erb
<% content_for(:title, "Edit #{@line.name} | Bus Timetable") %>

<h1> Edit <%= @line.name %> </h1>
<hr>

<%= render("layouts/form", :object => @line) %>

<%= link_to "Back", lines_path, :class=> "tiny button" %>

app/views/lines/index.html.erb
<% content_for(:title, "All Lines | Bus Timetable") %>

<h1> Lines </h1>
<hr>
<ul>
<% @lines.each do |line| %>
  <li><%= link_to "#{line.name}", line_path(line) %></li>
<% end %>
</ul>

<%=link_to "New Line", new_line_path, :class => "tiny button " %>
<%= link_to "Back", publics_path, :class => "tiny button" %>

app/views/lines/new.html.erb
<% content_for(:title, "Add Lines | Bus Timetable") %>

<h1> New Lines </h1>
<hr>

<%= render("layouts/form", :object => @line) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/lines/show.html.erb
<% content_for(:title, "#{@line.name} | Bus Timetable") %>

<h1><%= @line.name %></h1>

<h3>Here are the stations for the <%= @line.name %> line:</h3>
<ul>
<% @line.stations.each do |station| %>
  <li><%= link_to "#{station.name}", station_path(station)%></li>
  <% end %>
</ul>
<p><%= link_to "Edit", edit_line_path, :class => "tiny button" %></p>
<p><%= link_to "Delete", line_path, :class => "tiny button", :confirm => "Are you serious?", :method => "delete" %>

<p><%= link_to "Back", publics_path, :class => "tiny button" %></p>

app/views/publics/index.html.erb
<% content_for(:title, "Main Page | Bus Timetable") %>

<h1> Bus Timetable </h1>
<hr>

<h3>Stations</h3>
<ul>
<% @stations.each do |station| %>
  <li><a href="/stations/<%= station.id %>"><%= station.name %></a></li>
<% end %>
</ul>

<h3>Lines</h3>
<ul>
<% @lines.each do |line| %>
  <li><a href="/lines/<%= line.id %>"><%= line.name %></a></li>
<% end %>
</ul>

app/views/stations/edit.html.erb
<% content_for(:title, "Edit #{@station.name} | Bus Timetable") %>

<h1> Edit <%= @station.name %> </h1>
<hr>

<%= render("layouts/form", :object => @station) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/stations/index.html.erb
<% content_for(:title, "All Stations | Bus Timetable") %>

<h1> Stations </h1>
<hr>
<ul>
<% @stations.each do |station| %>
  <li><a href="/stations/<%= station.id %>"><%= station.name %></a></li>
<% end %>
</ul>

<%=link_to "New Station", new_station_path, :class => "tiny round button" %>
<%=link_to "New Line", new_line_path, :class => "tiny round success button" %>
<%=link_to "New Stop", new_stop_path, :class => "tiny round alert button" %>

app/views/stations/new.html.erb
<% content_for(:title, "Add Stations | Bus Timetable") %>

<h1> New Stations </h1>
<hr>

<%= render("layouts/form", :object => @station) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/stations/show.html.erb
<% content_for(:title, "#{@station.name} | Bus Timetable") %>

<h1><%= @station.name %></h1>
<h3>Here are the available lines at <%= @station.name %>:</h3>
<ul>
  <% @lines.each do |line| %>
   <li><%= link_to "#{line.name}", line_path(line) %></li>
  <% end %>
</ul>
<p><%= link_to "Edit", edit_station_path, :class => "tiny button" %></p>
<p><%= link_to "Delete", station_path, :class => "tiny button", :confirm => "Are you serious?", :method => "delete" %>

<p><%= link_to "Back", publics_path, :class => "tiny button" %></p>

app/views/stops/edit.html.erb
<% content_for(:title, "Edit Stop | Bus Timetable") %>

<h1> Edit Stop </h1>
<hr>

<%= render("layouts/stop_form", :object => @stop) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/stops/index.html.erb
<% content_for(:title, "All Stops | Bus Timetable") %>

<h1> Stops </h1>
<hr>
<ul>
<% @stops.each do |stop| %>
  <li><a href="/stops/<%= stop.id %>"><%= "Station: "+ stop.station.name + "   Line: " + stop.bus.line.name %></a></li>
<% end %>
</ul>

<%=link_to "New Station", new_station_path, :class => "tiny round button" %>
<%=link_to "New Line", new_line_path, :class => "tiny round success button" %>
<%=link_to "New Stop", new_stop_path, :class => "tiny round alert button" %>

app/views/stops/new.html.erb
<% content_for(:title, "Add Stop | Bus Timetable") %>

<h1> New Stop </h1>
<hr>

<%= render("layouts/stop_form", :object => @stop) %>

<%= link_to "Back", publics_path, :class=> "tiny button" %>

app/views/stops/show.html.erb
<% content_for(:title, "Stop Listing | Bus Timetable") %>

<h1>Stop Listing</h1>

<p><%= link_to "Edit", edit_stop_path(@stop), :class => "tiny button" %></p>
<p><%= link_to "Delete", stop_path, :class => "tiny button", :confirm => "Are you serious?", :method => "delete" %>

<p><%= link_to "Back", publics_path, :class => "tiny button" %></p>